### ISSUE TITLE
Doesn't work on the MathJax sample webpage or OpenGL doc site

### ISSUE THREAD

**Issue by Lotharyx** [andrusha/mathml-chrome#3]
URL: http://www.mathjax.org/demos/mathml-samples/

Make sure "MathML" is selected from the "rendering mode" option.

Chrome version: 30.0.1599.69 m
OS: Windows 7 Professional + SP1

Also has no effect on XSLT-rendered pages (observe http://www.opengl.org/sdk/docs/man2/xhtml/gluPerspective.xml , which is what I was trying to get it to work on in the first place)

**Comment by andrusha** [comment]
The 2.0 version should address this problem
